name: Asset gen on tag

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    tags:
      - v*

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: pdflatex 1
        uses: dante-ev/latex-action@latest
        with:
          root_file: TFM.tex
          compiler: pdflatex
          working_directory: src
          args: -interaction=nonstopmode -shell-escape
      - name: makeglossaries main
        uses: dante-ev/latex-action@latest
        with:
          root_file: TFM.glo
          compiler: makeglossaries
          working_directory: src
          args: ""
      - name: bibtex main
        uses: dante-ev/latex-action@latest
        with:
          root_file: TFM.aux
          compiler: bibtex
          working_directory: src
          args: ""
      - name: pdflatex 2
        uses: dante-ev/latex-action@latest
        with:
          root_file: TFM.tex
          compiler: pdflatex
          working_directory: src
          args: -interaction=nonstopmode -shell-escape
      - name: pdflatex 3
        uses: dante-ev/latex-action@latest
        with:
          root_file: TFM.tex
          compiler: pdflatex
          working_directory: src
          args: -interaction=nonstopmode -shell-escape
      # Create Release and upload the pdf as asset.
      - name: Release & Assets
        uses: Hs1r1us/Release-AIO@v1.0
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          asset_files: 'src/TFM.pdf'

