name: LaTeX - PDF Generation

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: pdflatex 1
        uses: dante-ev/latex-action@latest
        with:
          root_file: TFM.tex
          compiler: pdflatex
          working_directory: src
          args: -interaction=nonstopmode -shell-escape
      - name: makeglossaries main
        uses: dante-ev/latex-action@latest
        with:
          root_file: TFM.glo
          compiler: makeglossaries
          working_directory: src
          args: ""
      - name: bibtex main
        uses: dante-ev/latex-action@latest
        with:
          root_file: TFM.aux
          compiler: bibtex
          working_directory: src
          args: ""
      - name: pdflatex 2
        uses: dante-ev/latex-action@latest
        with:
          root_file: TFM.tex
          compiler: pdflatex
          working_directory: src
          args: -interaction=nonstopmode -shell-escape
      - name: pdflatex 3
        uses: dante-ev/latex-action@latest
        with:
          root_file: TFM.tex
          compiler: pdflatex
          working_directory: src
          args: -interaction=nonstopmode -shell-escape
      # Upload the PDF file as Artifact
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.0.0
        with:
          # Artifact name
          name: TFM.pdf
          path: src/TFM.pdf

